#!/usr/bin/env python3
"""AquaOS font rasterizer.

Default: anti-aliased monospace bitmap font from a system TTF -> font.h
  (terminal grid, 8-bit alpha coverage per pixel).
With --ui: two proportional UI fonts (regular + bold) -> font_ui.h
  (menu bar / titles / dialogs; per-glyph ink crop, bearing and advance).
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

MONO_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
]
UI_REG_CANDIDATES = [
    "/usr/share/fonts/truetype/english/Carlito-Regular.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
]
UI_BOLD_CANDIDATES = [
    "/usr/share/fonts/truetype/english/Carlito-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
]
FIRST, COUNT = 32, 95          # ASCII printable


def raster_mono(ttf, px):
    font = ImageFont.truetype(ttf, px)
    ascent, descent = font.getmetrics()
    cell_w = max(1, round(font.getlength("M")))
    cell_h = ascent + descent
    glyphs = []
    for i in range(COUNT):
        img = Image.new("L", (cell_w, cell_h), 0)
        d = ImageDraw.Draw(img)
        d.text((0, 0), chr(FIRST + i), font=font, fill=255)
        glyphs.append(bytes(img.getdata()))
    return cell_w, cell_h, glyphs


def write_mono(dst, ttf, px):
    cell_w, cell_h, glyphs = raster_mono(ttf, px)
    with open(dst, "w") as f:
        f.write("/* generated by mkfont.py from %s @ %dpx - do not edit */\n"
                % (ttf, px))
        f.write("#define FONT_W %d\n" % cell_w)
        f.write("#define FONT_H %d\n" % cell_h)
        f.write("#define FONT_FIRST %d\n" % FIRST)
        f.write("#define FONT_COUNT %d\n" % COUNT)
        f.write("static const unsigned char "
                "FONT_BITMAP[FONT_COUNT][FONT_H][FONT_W] = {\n")
        for g in glyphs:
            f.write("{\n")
            for y in range(cell_h):
                row = g[y * cell_w:(y + 1) * cell_w]
                f.write("{" + ",".join(str(v) for v in row) + "},\n")
            f.write("},\n")
        f.write("};\n")
    print("font.h: %s @ %dpx, cell %dx%d" % (os.path.basename(ttf), px,
                                             cell_w, cell_h))


def raster_prop(ttf, px):
    """Per-glyph: advance, ink offset relative to the pen origin, ink bitmap."""
    font = ImageFont.truetype(ttf, px)
    ascent, descent = font.getmetrics()
    cell_h = ascent + descent
    out = []
    maxw = maxh = 0
    for i in range(COUNT):
        ch = chr(FIRST + i)
        adv = int(round(font.getlength(ch)))
        pad = 6
        img = Image.new("L", (int(adv) + 2 * pad, cell_h + 2 * pad), 0)
        d = ImageDraw.Draw(img)
        d.text((pad, pad), ch, font=font, fill=255)
        bbox = img.getbbox()
        if bbox:
            x0, y0, x1, y1 = bbox
            ox, oy = x0 - pad, y0 - pad
            gw, gh = x1 - x0, y1 - y0
            rows = [bytes(img.crop(bbox).tobytes()[y * gw:(y + 1) * gw])
                    for y in range(gh)]
            # crop(...) already yields exactly gw*gh bytes row-major
            raw = img.crop(bbox).tobytes()
            rows = [raw[y * gw:(y + 1) * gw] for y in range(gh)]
        else:
            ox = oy = gw = gh = 0
            rows = []
        maxw = max(maxw, gw)
        maxh = max(maxh, gh)
        out.append((adv, ox, oy, gw, gh, rows))
    return cell_h, maxw, maxh, out


def write_ui(dst, reg_ttf, bold_ttf, px):
    cell_h, maxw, maxh, reg = raster_prop(reg_ttf, px)
    _, _, _, bold = raster_prop(bold_ttf, px)

    def emit(f, tag, glyphs):
        f.write("static const unsigned char %s_GW[UIF_COUNT] = {%s};\n"
                % (tag, ",".join(str(g[3]) for g in glyphs)))
        f.write("static const unsigned char %s_GH[UIF_COUNT] = {%s};\n"
                % (tag, ",".join(str(g[4]) for g in glyphs)))
        f.write("static const signed char %s_OX[UIF_COUNT] = {%s};\n"
                % (tag, ",".join(str(g[1]) for g in glyphs)))
        f.write("static const signed char %s_OY[UIF_COUNT] = {%s};\n"
                % (tag, ",".join(str(g[2]) for g in glyphs)))
        f.write("static const unsigned char %s_ADV[UIF_COUNT] = {%s};\n"
                % (tag, ",".join(str(g[0]) for g in glyphs)))
        f.write("static const unsigned char "
                "%s_BM[UIF_COUNT][UIF_MAXH][UIF_MAXW] = {\n" % tag)
        for adv, ox, oy, gw, gh, rows in glyphs:
            f.write("{\n")
            for y in range(maxh):
                if y < gh:
                    row = rows[y] + b"\0" * (maxw - gw)
                else:
                    row = b"\0" * maxw
                f.write("{" + ",".join(str(v) for v in row) + "},\n")
            f.write("},\n")
        f.write("};\n")

    with open(dst, "w") as f:
        f.write("/* generated by mkfont.py from %s + %s @ %dpx - do not edit */\n"
                % (reg_ttf, bold_ttf, px))
        f.write("#define UIF_FIRST %d\n" % FIRST)
        f.write("#define UIF_COUNT %d\n" % COUNT)
        f.write("#define UIF_CELLH %d\n" % cell_h)
        f.write("#define UIF_MAXW %d\n" % maxw)
        f.write("#define UIF_MAXH %d\n" % maxh)
        emit(f, "UIF", reg)
        emit(f, "UIFB", bold)
    print("font_ui.h: %s + %s @ %dpx, cell_h %d, max ink %dx%d"
          % (os.path.basename(reg_ttf), os.path.basename(bold_ttf), px,
             cell_h, maxw, maxh))


def main():
    argv = sys.argv[1:]
    if argv and argv[0] == "--ui":
        reg = next((p for p in UI_REG_CANDIDATES if os.path.exists(p)), None)
        bold = next((p for p in UI_BOLD_CANDIDATES if os.path.exists(p)), None)
        if not reg or not bold:
            raise SystemExit("no UI TTF found")
        px = int(argv[2]) if len(argv) > 2 else 13
        write_ui(argv[1], reg, bold, px)
        return
    src = next((p for p in MONO_CANDIDATES if os.path.exists(p)), None)
    if not src:
        raise SystemExit("no mono TTF found")
    dst = argv[0]
    px = int(argv[1]) if len(argv) > 1 else 13
    write_mono(dst, src, px)


if __name__ == "__main__":
    main()
