#!/usr/bin/env python3
"""AquaOS: rasterize an anti-aliased monospace bitmap font from a system TTF.
Produces font.h with 8-bit alpha coverage per pixel (smooth, not blocky)."""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

TTF_CANDIDATES = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
]
FIRST, COUNT = 32, 95          # ASCII printable


def main():
    src = next((p for p in TTF_CANDIDATES if os.path.exists(p)), None)
    if not src:
        raise SystemExit("no TTF found")
    dst = sys.argv[1]
    px = int(sys.argv[2]) if len(sys.argv) > 2 else 13

    font = ImageFont.truetype(src, px)
    ascent, descent = font.getmetrics()
    cell_w = max(1, round(font.getlength("M")))
    cell_h = ascent + descent

    glyphs = []
    for i in range(COUNT):
        img = Image.new("L", (cell_w, cell_h), 0)
        d = ImageDraw.Draw(img)
        d.text((0, 0), chr(FIRST + i), font=font, fill=255)
        glyphs.append(bytes(img.getdata()))

    with open(dst, "w") as f:
        f.write("/* generated by mkfont.py from %s @ %dpx - do not edit */\n" % (src, px))
        f.write("#define FONT_W %d\n" % cell_w)
        f.write("#define FONT_H %d\n" % cell_h)
        f.write("#define FONT_FIRST %d\n" % FIRST)
        f.write("#define FONT_COUNT %d\n" % COUNT)
        f.write("static const unsigned char FONT_BITMAP[FONT_COUNT][FONT_H][FONT_W] = {\n")
        for g in glyphs:
            f.write("{\n")
            for y in range(cell_h):
                row = g[y * cell_w:(y + 1) * cell_w]
                f.write("{" + ",".join(str(v) for v in row) + "},\n")
            f.write("},\n")
        f.write("};\n")
    print("font.h: %s @ %dpx, cell %dx%d" % (os.path.basename(src), px, cell_w, cell_h))


if __name__ == "__main__":
    main()
