#!/usr/bin/env python3
"""AquaOS: convert the dock icon PNG into a C header (RGBA8888 array)."""
import sys
from PIL import Image


def main():
    src, dst, prefix = sys.argv[1], sys.argv[2], sys.argv[3].upper()
    im = Image.open(src).convert("RGBA")
    w, h = im.size
    px = im.tobytes()
    with open(dst, "w") as f:
        f.write("/* generated by mkicon.py from %s - do not edit */\n" % src)
        f.write("#define %s_W %d\n" % (prefix, w))
        f.write("#define %s_H %d\n" % (prefix, h))
        f.write("static const unsigned char %s_DATA[%d] = {\n" % (prefix, w * h * 4))
        for i in range(0, len(px), 16):
            chunk = px[i:i + 16]
            f.write("    " + ",".join(str(b) for b in chunk) + ",\n")
        f.write("};\n")
    print("%s: %s -> %s (%dx%d RGBA)" % (prefix, src, dst, w, h))


if __name__ == "__main__":
    main()
