#!/usr/bin/env python3
"""AquaOS: convert the dock icon PNG into a C header (RGBA8888 array)."""
import sys
from PIL import Image


def main():
    src, dst = sys.argv[1], sys.argv[2]
    im = Image.open(src).convert("RGBA")
    w, h = im.size
    px = im.tobytes()
    with open(dst, "w") as f:
        f.write("/* generated by mkicon.py from %s - do not edit */\n" % src)
        f.write("#define ICON_W %d\n" % w)
        f.write("#define ICON_H %d\n" % h)
        f.write("static const unsigned char ICON_DATA[%d] = {\n" % (w * h * 4))
        for i in range(0, len(px), 16):
            chunk = px[i:i + 16]
            f.write("    " + ",".join(str(b) for b in chunk) + ",\n")
        f.write("};\n")
    print(f"terminal_icon.h: {src} -> {dst} ({w}x{h} RGBA)")


if __name__ == "__main__":
    main()
